# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9af429d57ca7109787c66c3c45a289014c5c8e8d28f0d6ea966da2bcaf96fdf62dd6dd002da4a5651c0048c391c97a44313bb34f34de44d3d149284353a62e61

test:
  secret_key_base: 7167069d1c6434b68bfe93e82fcabca2c1c314416dad91aeff93b9b57a34ea35b605735279952382bba9a147ab2a6b3e1208d7c0891356cb500ed5f31cbe474f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
