# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe30e9d7cc9a6053d2a997f5fc8efe8fef90f3b54938155c8a01821ce94e6343468c9b99dbff8e7cb8ba6b1317ee689e8a90f799c96cecde70c81869849988cd

test:
  secret_key_base: f62a30fbf16f1d7a1fd525fc39db641918a3a964caf11bca1667bb4d027be85ed81f903b293498fb1d15fc38dbb005005b98983e7c924f3a471830d1eff5d7d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
