# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 038def0a71c4ea7b9e7e3d2422ced6e84899b70a233ca1928e41f9ee4b3d91bb4eba5f42863b8cc125e6b411ebdc506028a94bb2a7afbbe8376b9bc3541c1044

test:
  secret_key_base: a9581a261628311b7c4aefdc45f9ac41a9656a2bf24fd261eb849aeb151c9d9bb34c96bcc6204f065e11f14144aef30344d4d3ecc472794dcdf4c86887ddedda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
