# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 810f8a8488517d9eebe35c6a6ab74b4991a2de545d0bf08ca7f4f9887f2ef06b249013fec6f855807bb41d1ef9a7720866066435f8fa0d001c153d14a5e2965f

test:
  secret_key_base: 8c52df43d36b5e6756ce2eed28473f8772ac1f038d05ef2a7451f342c866b7a81e49e541c39c4621fe99ae0c9340a9db087798969ae58451df8b632abadf5476

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
