# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd981ba2c5dd85e91074b3fe67116fc476c85c527742b06b8c2305d5ff81457af726dfb7eca6a8f69a3a85bf8b44009cf9ab30a69282885e6bd1b9aecc5ddf55

test:
  secret_key_base: a251cfb7c17503ec3aaecbc41fdfb611118c012ceee640cca05052686b10f416dae5287d2b7e424d0bccca858947cafdce18e13e552db4a7539ba2ceecb798e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
