# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cba7c8c4c9f63e77b129d7280c16f65eb68667ede1f0a70afa8c53ab13251be6e7a3d8884a73ef6bbb653c56d7db432b02d299eb61bd1fae05ba8bd515d7c51f

test:
  secret_key_base: 53f8ce8e624a0077e451889baf214d672e1ce565b49251a181a8cacae031d62dccb913f1a1f2ca46e0a3af98a57f8c0b81381e21b7aee5b3b1952ca54ef60dff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
