# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d068e17e53adb2f58c003fad14c527ba862b40f92ca22374829a8fffe70d217747594dcd4925ccfc105ba696ade9fd0c00c617cdad3b4649ce1aaf2acac97181

test:
  secret_key_base: 737b31d9fa86edcc021f619f19cdf7ff5da1afb0492b35b9ddb506412abb5b7b1dc07fd5c45019150fdc519faeab61f3c480b18ab28b5ec7e3b2e6ba0919c0d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
