# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 787d741b020d928e576c4e0fe732d4736c901708c92798a6b5c1029786582b89bc4af3d2e69056e1c1bc8a075a7cc7404beaa718960416673fe81fc4a139e20b

test:
  secret_key_base: 65a70cbc17d98554a843af2d26ffc4fc1c99fa738d9810a838f4a103b170306f0c7d53f2a6d97c3f889ebe812e85b5a8e991fb3da07edc5e196518d39a551f11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
